include theme.conf

font_family CaskaydiaCove Nerd Font
font_size   11.25

hide_window_decorations yes
background_opacity 0.8
enable_audio_bell no

# ANSI palette matching alacritty's built-in defaults
color0  #1d1f21
color1  #cc6666
color2  #b5bd68
color3  #f0c674
color4  #81a2be
color5  #b294bb
color6  #8abeb7
color7  #c5c8c6
color8  #666666
color9  #d54e53
color10 #b9ca4a
color11 #e7c547
color12 #7aa6da
color13 #c397d8
color14 #70c0b1
color15 #eaeaea
