require('marcel_nvim.plugins.packer').setup()
require('marcel_nvim.plugins.lsp').setup()
require('marcel_nvim.plugins.compe').setup()
require('marcel_nvim.plugins.treesitter').setup()
require('marcel_nvim.settings').setup_global()
require('marcel_nvim.commands').setup_global()
require('marcel_nvim.bindings').setup_global()
