ulimit -n 10240
bindkey -e

PROMPT='%2~ %# '
export EDITOR="nvim"
export CDPATH=.:~/g
export KEYTIMEOUT=1

alias startdev="limactl start dev0"
alias stopdev="limactl stop dev0"
alias dev="limactl shell --workdir . dev0"

if [ -f ~/.zsh_local ]; then
  . ~/.zsh_local
fi
