if [ -f ~/.bash_local ]; then
  . ~/.bash_local
fi

aws_vault_prompt() {
    if [[ -n "$AWS_VAULT" ]]; then
        echo "($AWS_VAULT) "
    fi
}

PS1='\w $(aws_vault_prompt)^ '

export PATH=$PATH:/usr/local/go/bin
export PATH=$HOME/go/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
export PATH="./node_modules/.bin:$PATH"

export NVIM_DARK=off
export NVIM_CMP=off

# Company specific
export GONOPROXY=$CONF_GNOPROXY
export GONOSUMDB=$CONF_GONOSUMDB
export GOPRIVATE=$CONF_GOPRIVATE
export NVIM_GOPLS_LOCAL=$CONF_NVIM_GOPLS_LOCAL

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias g='git'
alias n='nerdctl'
alias gdalb='git branch | grep -v "master" | xargs git branch -D'
alias ports='sudo lsof -P -i TCP -s TCP:LISTEN'
alias nrm="nerdctl ps | sed 1d | awk '{ print \$1 }' | xargs -r -I {} sh -c 'nerdctl stop {}; nerdctl rm -v {}'"

function kmode {
  if [[ "$1" == "rancher" ]]; then
    [[ "$2" != "-q" ]] && echo "Using rancher kubectl"
  else
    alias k='kubectl'
    [[ "$2" != "-q" ]] && echo "Using regular kubectl"
  fi
  
  # Update all aliases to use 'k'
  alias kgp='k get pods'
  alias kgs='k get svc'
  alias kgn='k get nodes'
  alias kdp='k describe pod'
  alias kds='k describe svc'
  alias kl='k logs'
  alias klf='k logs -f'
  alias kex='k exec -it'
  alias kaf='k apply -f'
  alias kdel='k delete'
  alias kgpa='k get pods --all-namespaces'
  alias kctx='k config use-context'
  alias kns='k config set-context --current --namespace'
  alias kcc='k config current-context'
  alias kcx='k config get-contexts'
  alias kcv='k config view --minify'
}

kmode regular -q

function kexec {
  kubectl exec -it $1 -- /bin/bash
}

# `source_env .env`
source_env() {
  # export $(echo $(cat $1 | sed 's/#.*//g'| xargs) | envsubst)
  export $(echo $(cat $1 | sed 's/#.*//g'| xargs) | envsubst)
  set -a # automatically export all variables
  source $1
  set +a
}

title() {
  if [ -z "$KITTY_WINDOW_ID" ]; then
    echo -e "\e]2;$1"
  else
    kitty @ set-tab-title $1
  fi
}

# OSC 52 clipboard copy
pbcopy() {
    printf "\033]52;c;$(cat | base64 | tr -d '\n')\a"
}

enable_proxy() {
  export http_proxy=$CONF_HTTP_PROXY
  export https_proxy=$CONF_HTTPS_PROXY
  export HTTP_PROXY=$CONF_HTTP_PROXY
  export HTTPS_PROXY=$CONF_HTTPS_PROXY
}

disable_proxy() {
  unset http_proxy
  unset https_proxy
  unset HTTP_PROXY
  unset HTTPS_PROXY
}

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# enable color support of ls and also add handy aliases
# if [ -x /usr/bin/dircolors ]; then
#     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#     alias ls='ls --color=auto'
#     #alias dir='dir --color=auto'
#     #alias vdir='vdir --color=auto'
# 
#     alias grep='grep --color=auto'
#     alias fgrep='fgrep --color=auto'
#     alias egrep='egrep --color=auto'
# fi

FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi
# Lima BEGIN
# Make sure iptables and mount.fuse3 are available
PATH="$PATH:/usr/sbin:/sbin"
export PATH
# Lima END

# fnm
FNM_PATH="/home/robotx.linux/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi
. "$HOME/.cargo/env"
