if [ -f ~/.bash_local ]; then
  . ~/.bash_local
fi

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

aws_vault_prompt() {
    if [[ -n "$AWS_VAULT" ]]; then
        echo "($AWS_VAULT) "
    fi
}

PS1='\w $(aws_vault_prompt)^ '

export PATH=$PATH:/$HOME/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$HOME/go/bin:$PATH
export PATH=$HOME/dev/zig:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH="$HOME/.local/share/nvim/mason/bin:$PATH"
export PATH="./node_modules/.bin:$PATH"

export EDITOR=nvim

# Company specific
export GONOPROXY=$CONF_GNOPROXY
export GONOSUMDB=$CONF_GONOSUMDB
export GOPRIVATE=$CONF_GOPRIVATE
export NVIM_GOPLS_LOCAL=$CONF_NVIM_GOPLS_LOCAL

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias g='git'
alias n='nerdctl'
alias d='docker'
alias gdalb='git branch | grep -v "master" | xargs git branch -D'
alias ports='sudo lsof -P -i TCP -s TCP:LISTEN'
alias nrm="nerdctl ps | sed 1d | awk '{ print \$1 }' | xargs -r -I {} sh -c 'nerdctl stop {}; nerdctl rm -v {}'"

# `source_env .env`
source_env() {
  # export $(echo $(cat $1 | sed 's/#.*//g'| xargs) | envsubst)
  export $(echo $(cat $1 | sed 's/#.*//g'| xargs) | envsubst)
  set -a # automatically export all variables
  source $1
  set +a
}

title() {
  if [ -z "$KITTY_WINDOW_ID" ]; then
    echo -e "\e]2;$1"
  else
    kitty @ set-tab-title $1
  fi
}

# OSC 52 clipboard copy
pbcopy() {
    printf "\033]52;c;$(cat | base64 | tr -d '\n')\a"
}

enable_proxy() {
  export http_proxy=$CONF_HTTP_PROXY
  export https_proxy=$CONF_HTTPS_PROXY
  export HTTP_PROXY=$CONF_HTTP_PROXY
  export HTTPS_PROXY=$CONF_HTTPS_PROXY
}

disable_proxy() {
  unset http_proxy
  unset https_proxy
  unset HTTP_PROXY
  unset HTTPS_PROXY
}

if [ -f ~/.bash_k8s ]; then
  . ~/.bash_k8s
fi

# enable color support of ls and also add handy aliases
# if [ -x /usr/bin/dircolors ]; then
#     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#     alias ls='ls --color=auto'
#     #alias dir='dir --color=auto'
#     #alias vdir='vdir --color=auto'
# 
#     alias grep='grep --color=auto'
#     alias fgrep='fgrep --color=auto'
#     alias egrep='egrep --color=auto'
# fi

FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi
# Lima BEGIN
# Make sure iptables and mount.fuse3 are available
PATH="$PATH:/usr/sbin:/sbin"
export PATH
# Lima END

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
