set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"
set -g set-clipboard on
set -g prefix C-a
# Prevent windows in hyprland getting focus on bell events cause by others.
set -g bell-action none
set -s escape-time 0
set -g mouse on
set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g status-left ""
set -g status-right "%Y-%m-%d %H:%M|#(date -u '+%%H:%%M')"

bind C-a send-prefix
bind r source-file ~/.tmux.conf
bind / set -g status
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-S-Left swap-window -t -1 \; select-window -t -1
bind -n M-S-Right swap-window -t +1 \; select-window -t +1

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind Left select-pane -L
bind Right select-pane -R
bind Up select-pane -U
bind Down select-pane -D